ExUnit.start()
ExUnit.configure(exclude: :wallaby)
Ecto.Adapters.SQL.Sandbox.mode(ElixirNewbie.Repo, :manual)
{:ok, _} = Application.ensure_all_started(:wallaby)
Application.put_env(:wallaby, :base_url, ElixirNewbieWeb.Endpoint.url())
