on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        elixir: [1.14.2]
        otp: [25.2, 25.1.2]

    steps:
    - uses: actions/checkout@v3
    - name: Setup elixir
      uses: actions/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]
    name: run tests
    steps:
      - run: mix deps.get
      - run: mix test